### ISSUE TITLE
[ISSUE] AccountClient for AzureDatabricks available?

### ISSUE THREAD

**Issue by jordandakota** [databricks/databricks-sdk-py#218]
**Description**
Is the AccountClient only available for AWS at the moment? Receiving nothing but Endpoint not found for /2.0/accounts/<account_id>/<endpoint> when trying to use any of the AccountClient methods.

**Reproduction**
```
# Use an azure databricks account and pass in appropriate variables
from databricks.sdk import AccountClient
from dotenv import load_dotenv
from os import getenv as env

load_dotenv("dd.env")

account_id = env("ACCOUNT_ID")
azure_workspace_resource_id = env("AZURE_WORKSPACE_RESOURCE_ID")
azure_tenant_id = env("AZURE_TENANT_ID")
azure_client_id = env("ACCOUNT_CLIENT_ID")
azure_client_secret = env("ACCOUNT_CLIENT_SECRET")

a = AccountClient(
    account_id=account_id,
    azure_workspace_resource_id=azure_workspace_resource_id,
    azure_tenant_id=azure_tenant_id,
    azure_client_id=azure_client_id,
    azure_client_secret=azure_client_secret,
    debug_headers=True,
)

billing = a.billable_usage.download(start_month="2023-06", end_month="2022-07")

```

**Expected behavior**
To be able to access any of the account methods like groups, users, billing, workspaces

**Debug Logs**
```
Traceback (most recent call last):
  File "c:\sdk\scripts\dd_get_billable_usage.py", line 25, in <module>
    billing = a.billable_usage.download(start_month="2023-06", end_month="2022-07")
  File "C:\Users\user\.virtualenvs\sdk-bqxZoST4\lib\site-packages\databricks\sdk\service\billing.py", line 492, in 
download
    self._api.do('GET', f'/api/2.0/accounts/{self._api.account_id}/usage/download', query=query)
  File "C:\Users\user\.virtualenvs\trino-bqxZoST4\lib\site-packages\databricks\sdk\core.py", line 932, in do
    raise self._make_nicer_error(status_code=response.status_code, **payload) from None
databricks.sdk.core.DatabricksError: Endpoint not found for /2.0/accounts/<account_id>/usage/download
```

**Other Information**
Windows 10

**Comment by nfx** [comment]
@jordandakota 

1. `DATABRICKS_ACCOUNT_ID`, not `ACCOUNT_ID`
2. you don't have to `azure_tenant_id = env("AZURE_TENANT_ID")`, because `AccountClient()` loads from environment variables by default. 
3. billable usage apis are not available on azure. only IAM and Unity Catalog APIs are available on account level for azure - see https://docs.databricks.com/api/azure/account/introduction - please try those and see if the issue persists

**Comment by slowder-bpcs** [comment]
While we can authenticate to Azure Databricks Account, we can't list/get/update workspaces.  Any ideas on when the Azure Account API will reach parity with the AWS version?

**Comment by manabian-** [comment]
I also ran the following code on Azure Databrick, but an error occurred.

```python
%pip install databricks-sdk --upgrade -q

dbutils.library.restartPython()

from databricks.sdk import WorkspaceClient
from databricks.sdk import AccountClient

w = WorkspaceClient()
account_client = AccountClient()

account_client.metastore_assignments.list(
    metastore_id = w.metastores.list()[0].metastore_id,
)
```

```text
DatabricksError: Endpoint not found for /2.0/accounts/None/metastores/b590278a-5927-XXXX-XXXX-XXXXXX/workspaces
```

<img width="482" alt="image" src="https://github.com/databricks/databricks-sdk-py/assets/10123723/a13a9222-5c5c-4f81-ac3a-894986531a87">

**Comment by shannonlowder** [comment]
The oct 3, 2023 code doesn't work for me either. Looks like a default AccountClient() or AccountClient(account_id=account_id) fails to retrieve anything through the account client.  When I add the account ID, it does change the message from account id none, to "Endpoint not found for /2.0/accounts/{account id redacted}/scim/v2/Groups"
