### ISSUE TITLE
[ISSUE] `Cluster [cluster_id] does not exist` error when trying to create a Job, however cluster exists and is running

### ISSUE THREAD

**Issue by rafaelvp-db** [databricks/databricks-sdk-py#252]
**Description**

`Cluster [cluster_id] does not exist` error when trying to create a Job, however cluster exists and is running

**Reproduction**

`create_job.py` example from `examples/jobs`

**Expected behavior**

Job is successfully created.

**Debug Logs**
```
Traceback (most recent call last):
  File "/Users/rafael.pierre/projects/workflows-model-serving-workshop/workflows/create_workflow.py", line 43, in <module>
    main()
  File "/Users/rafael.pierre/projects/workflows-model-serving-workshop/workflows/create_workflow.py", line 20, in main
    cluster_id = w.clusters.ensure_cluster_is_running(
  File "/Users/rafael.pierre/projects/workflows-model-serving-workshop/.venv/lib/python3.10/site-packages/databricks/sdk/mixins/compute.py", line 209, in ensure_cluster_is_running
    info = self.get(cluster_id)
  File "/Users/rafael.pierre/projects/workflows-model-serving-workshop/.venv/lib/python3.10/site-packages/databricks/sdk/service/compute.py", line 4045, in get
    json = self._api.do('GET', '/api/2.0/clusters/get', query=query)
  File "/Users/rafael.pierre/projects/workflows-model-serving-workshop/.venv/lib/python3.10/site-packages/databricks/sdk/core.py", line 939, in do
    raise self._make_nicer_error(status_code=response.status_code, **payload) from None
databricks.sdk.core.DatabricksError: Cluster 0727-054928-41plse7n does not exist
```

**Other Information**

 - OS: [e.g. macOS]
 - Version: [e.g. 0.1.0]

**Additional context**
Attached screenshot

![Screenshot 2023-07-27 at 08 04 50](https://github.com/databricks/databricks-sdk-py/assets/97888102/f89d9f42-9f98-49b4-95b1-9718f412d396)

**Comment by mgyucht** [comment]
What version of the SDK are you using?
The obvious question: are you sure you're using the right authentication? The examples will load the profile named "DEFAULT" from your ~/.databrickscfg file. That may be pointing to a different workspace.
Can you include the debug logs in addition to the stack trace? That will include the request URI and body which can help us diagnose whether the issue is in the SDK or backend service.

**Comment by rafaelvp-db** [comment]
@mgyucht I believe authentication wise all is good, I've replaced the auth from the examples and I'm passing the host and PAT token I created.

I noticed that I'm able to list all clusters from the workspace (using the SDK), however the one I wanna use for the example doesn't show up in that list. Is there any restriction in terms of the access mode for clusters to show up in that list (e.g. Single User etc)?

**Comment by mgyucht** [comment]
No, the list clusters API in the SDK simply returns the results from listing clusters using the REST API. There may be an issue with the clusters API then. I'll ask them to take a look at this issue.

**Comment by rafaelvp-db** [comment]
All right, so after some tweaking I was able to make it work.

Some comments:

1. When I try the `list_clusters` example I get the following:

```python
all = w.clusters.list(compute.ListClustersRequest())
```

```bash
Traceback (most recent call last):
  File "/Users/rafael.pierre/sdk-test/test.py", line 9, in <module>
    all = w.clusters.list(compute.ListClustersRequest())
TypeError: ClustersAPI.list() takes 1 positional argument but 2 were given
```

When I remove the parameter (`compute...`), I'm able to find my cluster.

2. For the `create_jobs_api_full_integration.py` example, the line below always returns `None` (removed the `os.environ` part for the sake of simplicity):

```python
cluster_id = w.clusters.ensure_cluster_is_running("0807-123938-mj2mzeq0") and "0807-123938-mj2mzeq0"
print(cluster_id)
```

If I just pass the cluster_id as a string it works:

```python
created_job = w.jobs.create(name=f'sdk-{time.time_ns()}',
                  tasks=[
                      jobs.Task(description="test",
                                #existing_cluster_id=cluster_id,
                                existing_cluster_id="0807-123938-mj2mzeq0",
                                notebook_task=jobs.NotebookTask(notebook_path=notebook_path),
                                task_key="test",
                                timeout_seconds=0)
                  ])
```

So probably a good idea to update the examples. But other than that, I guess this can be closed.

Thanks for the support @mgyucht !

**Comment by mgyucht** [comment]
Thanks @rafaelvp-db! The examples are autogenerated but we don't have good checking of them today. I'll create an AI to look into this as part of the stabilization of the Python SDK.
