### ISSUE TITLE
[ISSUE] Statement Execute API - Get Result Chunk By Index

### ISSUE THREAD

**Issue by GaniMarquez** [databricks/databricks-sdk-py#255]
**Description**
There is a missing query parameter when calling this API method using the SDK. It is looking for the `row_offset` in the query parameters.

**Reproduction**
```python
from databricks.sdk import WorkspaceClient
from databricks.sdk.service.sql import Disposition, Format


w = WorkspaceClient()

warehouse_id = "XXXXXX"

statement = w.statement_execution.execute_statement(
    disposition=Disposition.EXTERNAL_LINKS,
    format=Format.CSV,
    statement=(
        "SELECT * "
        "FROM table"
    ),
    warehouse_id=warehouse_id,
    wait_timeout="50s",
)

for chunk in statement.manifest.chunks:
    result = w.statement_execution.get_statement_result_chunk_n(
        statement.statement_id, chunk.chunk_index
    )
```

**Expected behavior**
I should be able to get the details of the next chunk of  results.

**Debug Logs**
```bash
Traceback (most recent call last):
  File "XXXXXXXXXXXXXXX/lib/python3.8/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "XXXXXXXXXXXXXXX/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "XXXXXXXXXXXXXXXcore/lifespan.py", line 27, in lifespan
    file_path = download_data_from_databricks(config.DATA_WAREHOUSE_NAME)
  File "XXXXXXXXXXXXXXXcore/databricks.py", line 49, in download_data_from_databricks
    result = w.statement_execution.get_statement_result_chunk_n(statement.statement_id, chunk.chunk_index)
  File "XXXXXXXXXXXXXXX/lib/python3.8/site-packages/databricks/sdk/service/sql.py", line 3457, in get_statement_result_chunk_n
    json = self._api.do(
  File "XXXXXXXXXXXXXXX/lib/python3.8/site-packages/databricks/sdk/core.py", line 939, in do
    raise self._make_nicer_error(status_code=response.status_code, **payload) from None
databricks.sdk.core.DatabricksError: Required field is not specified: row_offset.
```

**Other Information**
databricks-sdk==0.2.1

**Comment by mgyucht** [comment]
Thanks for raising this. I've raised a ticket with the team responsible for this endpoint to correct their API definition.

**Comment by vdelbaen** [comment]
Same issue here with databricks-sdk==0.3.0
It would be nice to have a fix as only the 1st chunk of data can be retrieved at the moment.
Thanks

**Comment by vdelbaen** [comment]
workaround:

`import requests
from databricks.sdk import WorkspaceClient
from databricks.sdk.service.sql import Disposition

DBRX_WORKSPACE = 'XXXXX'
DBRX_TOKEN = 'XXXXX'
HEADERS = {"Authorization": f'Bearer {DBRX_TOKEN}'}
warehouse_id = 'XXXXX'
sql_str = "SELECT * FROM table"

w = WorkspaceClient()
r = w.statement_execution.execute_statement(warehouse_id=warehouse_id, statement=sql_str, disposition=Disposition.INLINE)

for chunk in r.manifest.chunks:
    r_chunk = requests.get(f'{DBRX_WORKSPACE}/api/2.0/sql/statements/{r.statement_id}/result/chunks/{chunk.chunk_index}?row_offset={str(chunk.row_offset)}', headers=HEADERS)`
