### ISSUE TITLE
[ISSUE] Error from API when using update_job_permissions

### ISSUE THREAD

**Issue by kolyarice** [databricks/databricks-sdk-py#286]
**Description**
I'm trying to use update_job_permissions to modify the ACL on a job to include a users group. I can append the group to the existing ACL, but submitting it returns the error 

> databricks.sdk.core.DatabricksError: Principal name not defined

**Reproduction**
```python
import copy
import logging
from databricks.sdk import WorkspaceClient
import databricks.sdk.service.jobs as js

logging.basicConfig(format='%(asctime)s %(levelname)s:%(message)s', datefmt='%m/%d/%Y %H:%M:%S', level=logging.INFO)
logging.getLogger('databricks.sdk').setLevel(logging.DEBUG)

w = WorkspaceClient()

target_job_id = 474927432378895
target_group = "wi_developers_dev"
target_permission_level = js.JobPermissionLevel.CAN_VIEW

current_acl = w.jobs.get_job_permissions(job_id = target_job_id)
new_acl = copy.deepcopy(current_acl)
new_acl.access_control_list.append(js.JobAccessControlRequest(group_name=target_group, permission_level=target_permission_level))
logging.info("new acl:")
logging.info(new_acl)

logging.info("attempting to apply updated ACL to job " + str(target_job_id))
w.jobs.update_job_permissions(job_id = target_job_id, access_control_list = [new_acl])
``` 

**Expected behavior**
I expected that the ACL would be applied. It's not clear whether applying the ACL overwrites the existing ACL or appends to it. I'm assuming it overwrites, thus the fetch/append process.

I also tried just applying the current_acl, but received the same error

**Debug Logs**
```
08/14/2023 15:31:54 INFO:new acl:
08/14/2023 15:31:54 INFO:JobPermissions(access_control_list=[JobAccessControlResponse(all_permissions=[JobPermission(inherited=True, inherited_from_object=['/jobs/'], permission_level=<JobPermissionLevel.CAN_MANAGE: 'CAN_MANAGE'>)], display_name=None, group_name='admins', service_principal_name=None, user_name=None), JobAccessControlResponse(all_permissions=[JobPermission(inherited=False, inherited_from_object=None, permission_level=<JobPermissionLevel.IS_OWNER: 'IS_OWNER'>)], display_name='WI_ETL_DEV', group_name=None, service_principal_name='321214c9-d875-4c15-9edc-e32394521317', user_name=None), JobAccessControlRequest(group_name='wi_developers_dev', permission_level=<JobPermissionLevel.CAN_VIEW: 'CAN_VIEW'>, service_principal_name=None, user_name=None)], object_id='/jobs/474927432378895', object_type='job')
08/14/2023 15:31:54 INFO:attempting to apply updated ACL to job 474927432378895
08/14/2023 15:31:54 DEBUG:PATCH /api/2.0/permissions/jobs/474927432378895
> {
>   "access_control_list": [
>     {
>       "access_control_list": [
>         {
>           "all_permissions": [
>             {
>               "inherited": true,
>               "inherited_from_object": [
>                 "/jobs/"
>               ],
>               "permission_level": "CAN_MANAGE"
>             }
>           ],
>           "group_name": "admins"
>         },
>         "... (2 additional elements)"
>       ],
>       "object_id": "/jobs/474927432378895",
>       "object_type": "job"
>     }
>   ]
> }
< 400 Bad Request
< {
<   "error_code": "INVALID_PARAMETER_VALUE",
<   "message": "Principal name not defined"
< }
Traceback (most recent call last):
  File "/mnt/c/Users/kolya/code/scripts/update_tables_owner_to_group.py", line 101, in <module>
    w.jobs.update_job_permissions(job_id = target_job_id, access_control_list = [new_acl])
  File "/home/amorphis/.local/lib/python3.10/site-packages/databricks/sdk/service/jobs.py", line 3641, in update_job_permissions
    json = self._api.do('PATCH', f'/api/2.0/permissions/jobs/{job_id}', body=body)
  File "/home/amorphis/.local/lib/python3.10/site-packages/databricks/sdk/core.py", line 963, in do
    raise self._make_nicer_error(status_code=response.status_code, **payload) from None
databricks.sdk.core.DatabricksError: Principal name not defined
```

**Other Information**
 - OS: Win11/WSL Ubuntu 22.04.2 LTS
 - databricks-sdk Version: 0.4.0

**Comment by kolyarice** [comment]
I just noticed that 0.5.0 was released. I upgraded but the behavior is the same as 0.4.0

**Comment by mgyucht** [comment]
@kolyarice I think there is at least one bug in your code: the SDK returns a `JobAccessControlResponse`, but you need to supply `JobAccessControlRequest`s to `update_job_permissions`.

**Comment by kolyarice** [comment]
thanks @mgyucht 
I changed new_acl to just the group to be added
The code succeeded, and the ACL was appended, not overwritten.
