### ISSUE TITLE
[ISSUE] Value Error thrown on oauth m2m authentication

### ISSUE THREAD

**Issue by dmoore247** [databricks/databricks-sdk-py#298]
**Description**
Running oauth m2m authentication to Account api, and response comes back as HTML
Indecipherable ValueError is thrown

**Reproduction**
```python
a = AccountClient(
  host          = account_host,
  account_id    = account_id,
  client_id     = client_id,
  client_secret = client_secret
)
```

**Expected behavior**
Expected account client connection object w/o prompt for oauth login browser popup.

**Debug Logs**
```
cd /Users/douglas.moore/developmen
t/switchrole ; /usr/bin/env /Users/douglas.moore/.pyenv/versions/3.10.10/
bin/python /Users/douglas.moore/.vscode/extensions/ms-python.python-2023.
15.12191008/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher
 54216 -- /Users/douglas.moore/development/switchrole/switch.py 
DEBUG:databricks.sdk:Attempting to configure auth: pat
DEBUG:databricks.sdk:Attempting to configure auth: basic
DEBUG:databricks.sdk:Attempting to configure auth: oauth-m2m
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): accounts.cloud.databricks.com:443
DEBUG:urllib3.connectionpool:https://accounts.cloud.databricks.com:443 "GET /oidc/.well-known/oauth-authorization-server HTTP/1.1" 303 0
DEBUG:urllib3.connectionpool:https://accounts.cloud.databricks.com:443 "GET /login?next_url=%2Foidc%2F.well-known%2Foauth-authorization-server HTTP/1.1" 200 439
DEBUG:charset_normalizer:Encoding detection: utf_8 is most likely the one.
DEBUG:charset_normalizer:Encoding detection: utf_8 is most likely the one.
```

**Other Information**
 - OS: macOS
 - Version: 0.1.6
 - Python: 3.10
 - Cloud: aws databricks

**Additional context**
Call Stack & resp.text
<img width="990" alt="image" src="https://github.com/databricks/databricks-sdk-py/assets/1122251/9575f4f5-6586-43ba-9861-8fe2d3fec61a">

**Comment by dmoore247** [comment]
```
% python switch.py 
DEBUG:databricks.sdk:Attempting to configure auth: pat
DEBUG:databricks.sdk:Attempting to configure auth: basic
DEBUG:databricks.sdk:Attempting to configure auth: oauth-m2m
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): accounts.cloud.databricks.com:443
DEBUG:urllib3.connectionpool:https://accounts.cloud.databricks.com:443 "GET /oidc/.well-known/oauth-authorization-server HTTP/1.1" 303 0
DEBUG:urllib3.connectionpool:https://accounts.cloud.databricks.com:443 "GET /login?next_url=%2Foidc%2F.well-known%2Foauth-authorization-server HTTP/1.1" 200 439
Traceback (most recent call last):
  File "/Users/douglas.moore/.pyenv/versions/3.10.10/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/douglas.moore/.pyenv/versions/3.10.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/douglas.moore/.pyenv/versions/3.10.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/douglas.moore/.pyenv/versions/3.10.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/douglas.moore/.pyenv/versions/3.10.10/lib/python3.10/site-packages/databricks/sdk/core.py", line 312, in __call__
    header_factory = provider(cfg)
  File "/Users/douglas.moore/.pyenv/versions/3.10.10/lib/python3.10/site-packages/databricks/sdk/core.py", line 59, in wrapper
    return func(cfg)
  File "/Users/douglas.moore/.pyenv/versions/3.10.10/lib/python3.10/site-packages/databricks/sdk/core.py", line 102, in oauth_service_principal
    token_url=resp.json()["token_endpoint"],
  File "/Users/douglas.moore/.pyenv/versions/3.10.10/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/douglas.moore/.pyenv/versions/3.10.10/lib/python3.10/site-packages/databricks/sdk/core.py", line 669, in _init_auth
    self._header_factory = self._credentials_provider(self)
  File "/Users/douglas.moore/.pyenv/versions/3.10.10/lib/python3.10/site-packages/databricks/sdk/core.py", line 318, in __call__
    raise ValueError(f'{auth_type}: {e}') from e
ValueError: oauth-m2m: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/douglas.moore/.pyenv/versions/3.10.10/lib/python3.10/site-packages/databricks/sdk/core.py", line 390, in __init__
    self._init_auth()
  File "/Users/douglas.moore/.pyenv/versions/3.10.10/lib/python3.10/site-packages/databricks/sdk/core.py", line 674, in _init_auth
    raise ValueError(f'{self._credentials_provider.auth_type()} auth: {e}') from e
ValueError: default auth: oauth-m2m: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/douglas.moore/development/switchrole/switch.py", line 18, in <module>
    a = AccountClient(
  File "/Users/douglas.moore/.pyenv/versions/3.10.10/lib/python3.10/site-packages/databricks/sdk/__init__.py", line 185, in __init__
    config = client.Config(host=host,
  File "/Users/douglas.moore/.pyenv/versions/3.10.10/lib/python3.10/site-packages/databricks/sdk/core.py", line 395, in __init__
    raise ValueError(message) from e
ValueError: default auth: oauth-m2m: Expecting value: line 1 column 1 (char 0).
```

**Comment by dmoore247** [comment]
Didn't expect login page, I may not understand how oauth-m2m works, but if that's what should happen, then a better error message would be nice.

**Comment by mgyucht** [comment]
The relevant code from the SDK, taken from databricks/sdk/core.py:
```py
        if self.is_account_client and self.account_id:
            prefix = f'{self.host}/oidc/accounts/{self.account_id}'
            return OidcEndpoints(authorization_endpoint=f'{prefix}/v1/authorize',
                                 token_endpoint=f'{prefix}/v1/token')
        oidc = f'{self.host}/oidc/.well-known/oauth-authorization-server'
        res = requests.get(oidc)
        if res.status_code != 200:
            return None
        auth_metadata = res.json()
        return OidcEndpoints(authorization_endpoint=auth_metadata.get('authorization_endpoint'),
                             token_endpoint=auth_metadata.get('token_endpoint'))
```
If correctly configured, AccountsClient should not be requesting OIDC endpoints from the .well-known endpoint; rather, they should be fixed. I can't see what is wrong with your code, but it could be that there is an issue with the account ID that you've provided (i.e. it is `None` or `""`).

**Comment by nfx** [comment]
I think that error means no OAuth is enabled/available for that account. There has to be UC there as well

**Comment by dmoore247** [comment]
Thanks @mgyucht 
My bad, again, wrong version of the SDK. :(

**Comment by dmoore247** [comment]
Closing - User Error
