### ISSUE TITLE
Issue when list_webhooks() is called

### ISSUE THREAD

**Issue by Dhanunjaya-Elluri** [databricks/databricks-sdk-py#313]
In the below code, I created a webhook, with the events I'm interested in while creating. However, when I try to list the webhooks, the following error occurs:

### code snippet
```python
from databricks.sdk import WorkspaceClient
from databricks.sdk.service import ml

dbx_client = WorkspaceClient(
    host="https://adb-xxx.12.azuredatabricks.net",
)

# Create webhook
webhook = dbx_client.model_registry.create_webhook(
    events=[
        ml.RegistryWebhookEvent.MODEL_VERSION_CREATED,
        ml.RegistryWebhookEvent.MODEL_VERSION_TRANSITIONED_STAGE,
    ],
    model_name="my-model",
    description="Sample model",
    http_url_spec=ml.HttpUrlSpec(
        url="https://app.azurewebsites.net/v1/deployments"
    ),
)

# List webhooks
webhooks = dbx_client.model_registry.list_webhooks(model_name="my-model") 
output = [webhook.as_dict() for webhook in webhooks] 
print(output)
```

### Error:
```bash
Traceback (most recent call last):
  File "C:\Users\jay\PycharmProjects\feature-branches\api-test\playground\main.py", line 56, in <module>
    output = [
  File "C:\Users\jay\PycharmProjects\feature-branches\api-test\playground\main.py", line 57, in <listcomp>
    webhook.as_dict() for webhook in webhooks
  File "C:\Program Files (x86)\conda3_2022\envs\py310\lib\site-packages\databricks\sdk\service\ml.py", line 1600, in as_dict   
    if self.events: body['events'] = [v.value for v in self.events]
  File "C:\Program Files (x86)\conda3_2022\envs\py310\lib\site-packages\databricks\sdk\service\ml.py", line 1600, in <listcomp>
    if self.events: body['events'] = [v.value for v in self.events]
AttributeError: 'str' object has no attribute 'value'
```

My interpretation is that the events are registered as strings rather than enums. 

Fix:
[databricks-sdk-py](https://github.com/databricks/databricks-sdk-py/tree/main)/[databricks](https://github.com/databricks/databricks-sdk-py/tree/main/databricks)/[sdk](https://github.com/databricks/databricks-sdk-py/tree/main/databricks/sdk)/[service](https://github.com/databricks/databricks-sdk-py/tree/main/databricks/sdk/service)
/ml.py

Line [1600](https://github.com/databricks/databricks-sdk-py/blob/e05c8c08679bae0d25fbccf4a0b0035edd4ed44e/databricks/sdk/service/ml.py#L1600C9-L1600C72)
```python
if self.events: body['events'] = self.events
```
This works for me. Please fix this issue :)

### Additional Information:

Python version: 3.10
Databricks SDK version: databricks-sdk==0.6.0

**Comment by mgyucht** [comment]
Thanks for raising this issue! We don't really exercise the `.as_dict()` method on response objects, as we are typically only deserializing them and not serializing them. We should be able to fix this in generated code.

**Comment by sh0rtcircuit** [comment]
I am facing the same issue, it would be great if this could be adressed! 😊
