### ISSUE TITLE
[ISSUE] Reading artifact allowlists does not work

### ISSUE THREAD

**Issue by liahagan** [databricks/databricks-sdk-py#325]
**Description**

The SDK is unable to get artifact allowlists, resulting in an error.

I've noticed that the schema in the [API doc](https://docs.databricks.com/api/azure/workspace/artifactallowlists/get) does not match the object that it actually returns. `artifact_matchers` is actually a list.

**Reproduction**

```python
from databricks.sdk import WorkspaceClient
from databricks.sdk.service.catalog import ArtifactType

w = WorkspaceClient()

init_script_allowlist = w.artifact_allowlists.get(ArtifactType.INIT_SCRIPT)
```

**Expected behavior**

The code above should not cause an error.

**Debug Logs**

*Some values have been redacted*

```
INFO:databricks.sdk:loading DEFAULT profile from ~/.databrickscfg: host, token
DEBUG:databricks.sdk:Attempting to configure auth: pat
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): adb-0000000000000000.00.azuredatabricks.net:443
DEBUG:urllib3.connectionpool:https://adb-0000000000000000.00.azuredatabricks.net:443 "GET /api/2.1/unity-catalog/artifact-allowlists/INIT_SCRIPT HTTP/1.1" 200 None
DEBUG:databricks.sdk:GET /api/2.1/unity-catalog/artifact-allowlists/INIT_SCRIPT
< 200 OK
< {
<   "artifact_matchers": [
<     {
<       "artifact": "/Volumes/fizz",
<       "match_type": "PREFIX_MATCH"
<     }
<   ],
<   "created_at": 1693426119354,
<   "created_by": "user@company.com",
<   "metastore_id": "00000000-0000-0000-0000-000000000000"
< }
Traceback (most recent call last):
  File "/Users/user/scripts/databricks_sdk.py", line 9, in <module>
    init_script_allowlist = w.artifact_allowlists.get(ArtifactType.INIT_SCRIPT)
  File "/Users/user/.local/share/virtualenvs/scripts-i_7zIFC6/lib/python3.10/site-packages/databricks/sdk/service/catalog.py", line 3499, in get
    return ArtifactAllowlistInfo.from_dict(res)
  File "/Users/user/.local/share/virtualenvs/scripts-i_7zIFC6/lib/python3.10/site-packages/databricks/sdk/service/catalog.py", line 182, in from_dict
    return cls(artifact_matchers=_from_dict(d, 'artifact_matchers', ArtifactMatcher),
  File "/Users/user/.local/share/virtualenvs/scripts-i_7zIFC6/lib/python3.10/site-packages/databricks/sdk/service/_internal.py", line 8, in _from_dict
    return getattr(cls, 'from_dict')(d[field])
  File "/Users/user/.local/share/virtualenvs/scripts-i_7zIFC6/lib/python3.10/site-packages/databricks/sdk/service/catalog.py", line 201, in from_dict
    return cls(artifact=d.get('artifact', None), match_type=_enum(d, 'match_type', MatchType))
AttributeError: 'list' object has no attribute 'get'
```

**Other Information**

 - OS: macOS 13.5.1
 - Version: 0.7.0
 - Cloud: Azure

**Comment by kartikgupta-db** [comment]
Hi @liahagan. Thanks for reporting this issue. This was indeed an issue in our API spec. We have fixed it and it should roll out in both the sdk and the API docs in their next releases.

**Comment by liahagan** [comment]
Verified that this issue has been fixed in the latest release, 0.9.0
