### ISSUE TITLE
[ISSUE] FunctionsAPI get() method is broken?

### ISSUE THREAD

**Issue by cpc-ruffin** [databricks/databricks-sdk-py#384]
**Description**
I am not sure if I am using the sdk wrong or not but the get() method for functions is not working for me. The documentation for the sdk is below:

get(name)
Get a function.

Gets a function from within a parent catalog and schema. For the fetch to succeed, the user must satisfy one of the following requirements: - Is a metastore admin - Is an owner of the function’s parent catalog - Have the USE_CATALOG privilege on the function’s parent catalog and be the owner of the function - Have the USE_CATALOG privilege on the function’s parent catalog, the USE_SCHEMA privilege on the function’s parent schema, and the EXECUTE privilege on the function itself

Parameters:
name – str The fully-qualified name of the function (of the form __catalog_name__.__schema_name__.__function__name__).

Returns:
Fun

**Reproduction**
I have listed both methods below and their respective error messages
w.functions.get(name="__<catalog>__.__<schema>__.__<function>__")
DatabricksError: CATALOG '__dev_seeq_realtime__' does not exist.
I have successfully ran w.catalogs.get() with the same catalog so it is not a configuration issue.

w.functions.get(name="<catalog>.<schema>.<function>")
AttributeError: 'str' object has no attribute 'get'

**Expected behavior**
I want to return the details of the function so I can recreate it in a different location.

**Other Information**
 - OS: [e.g. macOS]
 - Version: [e.g. 0.1.0]

**Additional context**
I am not sure if I am formatting my call wrong because there are not examples for the function section like there is for other sections.

**Comment by cpc-ruffin** [comment]
**EDIT**
The underscores didn't escape properly in my description, but the name parameter expects the levels of the functions (catalog, schema, functions) to be separated by double underscores. For more clarification look at the documentation of the get() method name parameter here:
https://databricks-sdk-py.readthedocs.io/en/latest/workspace/functions.html

Also my reproduction section did not copy correctly either. But I was specifying that I tried with and without the double underscore separation.

**Comment by themattmorris** [comment]
I'm running into the same situation.

```python
from databricks.sdk import WorkspaceClient

w = WorkspaceClient()

function_info = w.functions.get("catalog.schema.function_name")
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/miniconda3/envs/310/lib/python3.10/site-packages/databricks/sdk/service/catalog.py", line 4104, in get
    return FunctionInfo.from_dict(res)
  File "~/miniconda3/envs/310/lib/python3.10/site-packages/databricks/sdk/service/catalog.py", line 1332, in from_dict
    input_params=_repeated(d, 'input_params', FunctionParameterInfo),
  File "~/miniconda3/envs/310/lib/python3.10/site-packages/databricks/sdk/service/_internal.py", line 15, in _repeated
    return [from_dict(v) for v in d[field]]
  File "~/miniconda3/envs/310/lib/python3.10/site-packages/databricks/sdk/service/_internal.py", line 15, in <listcomp>
    return [from_dict(v) for v in d[field]]
  File "~/miniconda3/envs/310/lib/python3.10/site-packages/databricks/sdk/service/catalog.py", line 1416, in from_dict
    return cls(comment=d.get('comment', None),
AttributeError: 'str' object has no attribute 'get'
```

This is for a known existing function.

Environment:
- Linux (rhel)
- `python==3.10.11`
- `databricks-sdk == 0.10.0`

It is failing to parse the `FunctionParameterInfo`.  **The function in question is a Python UDF**.  Could it be that the `FunctionParameterInfo` is expecting a SQL UDF (which perhaps returns a dict instead of a string)?

**Comment by themattmorris** [comment]
It is also worth mentioning that I'm able to see this function using `w.functions.list()`...here is what the `FunctionInfo` looks like for it (with certain unimportant attributes masked):

```python
FunctionInfo(catalog_name='my_catalog',
             comment='Check if a year is a leap year.',
             created_at=1696442714173,
             created_by='first.last@domain.com',
             data_type=<ColumnTypeName.BOOLEAN: 'BOOLEAN'>,
             external_language='Python',
             external_name=None,
             full_data_type='BOOLEAN',
             full_name='my_catalog.my_schema.isleapyear',
             function_id='********-****-****-****-************',
             input_params=None,
             is_deterministic=True,
             is_null_call=None,
             metastore_id='********-****-****-****-************',
             name='isleapyear',
             owner='first.last@domain.com',
             parameter_style=None,
             properties='{"sqlConfig.spark.sql.legacy.createHiveTableByDefault":"false","sqlConfig.spark.sql.streaming.stopTimeout":"15s","sqlConfig.spark.sql.sources.default":"delta","sqlConfig.spark.sql.hive.convertCTAS":"true","sqlConfig.spark.sql.sources.commitProtocolClass":"com.databricks.sql.transaction.directory.DirectoryAtomicCommitProtocol","sqlConfig.spark.sql.parquet.compression.codec":"snappy"}',
             return_params=None,
             routine_body=<FunctionInfoRoutineBody.EXTERNAL: 'EXTERNAL'>,
             routine_definition='\n'
                                '    import calendar\n'
                                '    return calendar.isleap(year)\n',
             routine_dependencies=None,
             schema_name='default',
             security_type=None,
             specific_name=None,
             sql_data_access=<FunctionInfoSqlDataAccess.NO_SQL: 'NO_SQL'>,
             sql_path=None,
             updated_at=1696442714173,
             updated_by='first.last@domain.com')
```

the python udf (from databricks docs):

```sql
CREATE FUNCTION `my_catalog`.`my_database`.`isleapyear`(year INT)
RETURNS BOOLEAN
LANGUAGE PYTHON
DETERMINISTIC
COMMENT 'Determine if a year is a leap year.'
AS $$
    import calendar
    return calendar.isleap(year)
$$
```

It's interesting that `input_params` are none in the `FunctinoInfo` above, though the python udf does take input parameters (year INT).

**Comment by themattmorris** [comment]
Sorry for another comment, but just noticing this...should `properties` be a `dict[str, str]` rather than a string?  See annotation:

https://github.com/databricks/databricks-sdk-py/blob/bb3095b510e0bbe6d74a4fe47fc1ee1803b00612/databricks/sdk/service/catalog.py#L1273

In the `FunctionInfo` that was returned above, I'm getting a string

**Comment by cpc-ruffin** [comment]
**UPDATE**
After messing around with the Databricks SDK I realized I am only getting this error for udfs in the default schema. When I use the get method for schemas that were manually created I do not get this issue. It is only for udfs in the default schema.

**Comment by mgyucht** [comment]
Thanks for reporting this. This is probably a mistake in the definition of our API. I will create a ticket for the owning team and ask them to correct this mistake.

**Comment by mgyucht** [comment]
@cpc-ruffin I think this should have been addressed by the underlying team. Could you double check if this succeeds on the most recent SDK version?
