### ISSUE TITLE
Error while using filter parameter in list operation

### ISSUE THREAD

**Issue by maiconbaum** [databricks/databricks-sdk-py#90]
Hello!

I'm not sure if I'm doing something wrong, but, while using the groups' `list` operation from WorkspaceClient:

```
03/05/2023 04:00:10 PM  :::DEBUG::::   Loaded from environment
03/05/2023 04:00:10 PM  :::DEBUG::::   Attempting to configure auth: pat
03/05/2023 04:00:10 PM  :::DEBUG::::   Starting new HTTPS connection (1): xxxxxxxxxxxx.cloud.databricks.com:443
03/05/2023 04:00:12 PM  :::DEBUG::::   https://xxxxxxxxxxxx.cloud.databricks.com:443 "GET /api/2.0/preview/scim/v2/Groups?filter=displayName%2Beq%2Bmy_group HTTP/1.1" 400 None
03/05/2023 04:00:12 PM  :::DEBUG::::   GET /api/2.0/preview/scim/v2/Groups?filter=displayName+eq+my_group
< 400 Bad Request
< {
<   "detail": "Given filter operator is not supported.",
<   "schemas": [
<     "urn:ietf:params:scim:api:messages:2.0:Error"
<   ],
<   "scimType": "InvalidFilter",
<   "status": "400"
< }
Traceback (most recent call last):
  File "<redacted>/main.py", line 6, in <module>
    databricks_groups = databricks_workspace.groups.list(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/databricks/sdk/service/iam.py", line 1291, in list
    json = self._api.do('GET', '/api/2.0/preview/scim/v2/Groups', query=query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/databricks/sdk/core.py", line 753, in do
    raise self._make_nicer_error(status_code=response.status_code, **payload) from None
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ApiClient._make_nicer_error() missing 1 required positional argument: 'message'
```

If I try the exact same filter using cURL, for example, everything works fine. 

This is the `main.py`:

```python
from databricks.sdk import WorkspaceClient
from modules.config.log import logger

databricks_workspace = WorkspaceClient()

databricks_groups = databricks_workspace.groups.list(
    filter="displayName+eq+my_group"
)
```

I'm using the SDK version `0.1.2` and Python version `3.11.3`.

**Comment by nfx** [comment]
Hi @maiconbaum , thanks for reporting this nasty bug related to SCIM API error deserialization! we'll pick it up tomorrow.

Meanwhile, debug string suggests that something is wrong with `filter`:
```
< 400 Bad Request
< {
<   "detail": "Given filter operator is not supported.",
<   "schemas": [
<     "urn:ietf:params:scim:api:messages:2.0:Error"
<   ],
<   "scimType": "InvalidFilter",
<   "status": "400"
< }
```

could you try `displayName eq my_group` (without `+`)?

**Comment by maiconbaum** [comment]
Just worked like a charm!

```python
from databricks.sdk import WorkspaceClient
from modules.config.log import logger

databricks_workspace = WorkspaceClient()

databricks_groups = databricks_workspace.groups.list(
    filter="displayName eq my_group"
)
```


Response:

```
03/05/2023 04:10:50 PM  :::DEBUG::::   Loaded from environment
03/05/2023 04:10:50 PM  :::DEBUG::::   Attempting to configure auth: pat
03/05/2023 04:10:50 PM  :::DEBUG::::   Starting new HTTPS connection (1): xxxxxxxxxxxxxxx:443
03/05/2023 04:10:52 PM  :::DEBUG::::   https://xxxxxxxxxxxxxxx:443 "GET /api/2.0/preview/scim/v2/Groups?filter=displayName+eq+my_group HTTP/1.1" 200 311
03/05/2023 04:10:52 PM  :::DEBUG::::   GET /api/2.0/preview/scim/v2/Groups?filter=displayName+eq+my_group
< 200 OK
< {
<   "Resources": [
<     {
<       "displayName": "my_group",
<       "groups": [],
<       "id": "xxxxxxxxxxxxxxxx",
<       "members": [
<         {
<           "$ref": "ServicePrincipals/xxxxxxxxxxxxxxxx",
<           "display": "my_group",
<           "value": "**REDACTED**"
<         }
<       ],
<       "meta": {
<         "resourceType": "Group"
<       },
<       "roles": [
<         {
<           "value": "**REDACTED**"
<         }
<       ]
<     }
<   ],
<   "itemsPerPage": 1,
<   "schemas": [
<     "urn:ietf:params:scim:api:messages:2.0:ListResponse"
<   ],
<   "startIndex": 1,
<   "totalResults": 1
< }
[Group(id='xxxxxxxxxxxxxxxx', display_name='my_group', entitlements=None, external_id=None, groups=None, members=[ComplexValue(display='my_group', primary=None, type=None, value='xxxxxxxxxxxxxxxx')], roles=[ComplexValue(display=None, primary=None, type=None, value='xxxxxxxxxxxxxxxx')])]
```

Thanks a lot, @nfx
